### ISSUE TITLE
Design - Update "Changes Saved" box in all of the Settings pages (2)

### ISSUE THREAD

**Issue by peggyzhouu** [Vuologist/bumpie#125]
DoD: Under "User Settings" text and "Notification Settings" text of the "User Settings" and "Notification Settings" page, have a box that shows when changes are saved. Removal of the "Changes Saved" page. Prototype so that all "SAVE" buttons transition to pages when changes are saved. (2) Ping @Vuologist

**Comment by Vuologist** [comment]
1. are the new changes wired up to the prototype
2. change second 'enter new password' to something like 'confirm new password'
3. change username artboard - can we remove the confirm password since it isn't a password change?
4. what are your thoughts on having the save button greyed out when no new content is present?
